# Generated by Django 2.2.7 on 2019-11-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ts_code', models.CharField(max_length=100, verbose_name='TS代码')),
                ('symbol', models.CharField(max_length=100, verbose_name='股票代码')),
                ('name', models.CharField(max_length=100, verbose_name='股票名称')),
                ('area', models.CharField(max_length=100, verbose_name='所在地域')),
                ('industry', models.CharField(max_length=100, verbose_name='所属行业')),
                ('fullname', models.CharField(max_length=100, verbose_name='股票全称')),
                ('enname', models.CharField(max_length=100, verbose_name='英文全称')),
                ('market', models.CharField(max_length=100, verbose_name='市场类型')),
                ('exchange', models.CharField(max_length=100, verbose_name='交易所代码')),
                ('curr_type', models.CharField(max_length=100, verbose_name='交易货币')),
                ('list_status', models.CharField(help_text='L上市 D退市 P暂停上市', max_length=100, verbose_name='上市状态')),
                ('list_date', models.CharField(max_length=100, verbose_name='上市日期')),
                ('delist_date', models.CharField(max_length=100, null=True, verbose_name='退市日期')),
                ('is_hs', models.CharField(help_text='N否 H沪股通 S深股通', max_length=100, verbose_name='是否沪深港通')),
            ],
            options={
                'verbose_name': '所有股票基本信息',
                'verbose_name_plural': '所有股票基本信息',
                'ordering': ('id',),
            },
        ),
    ]
