# Generated by Django 2.2.7 on 2019-11-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wealth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='area',
            field=models.CharField(max_length=100, null=True, verbose_name='所在地域'),
        ),
    ]
