# Generated by Django 2.2.7 on 2019-11-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wealth', '0002_auto_20191112_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='industry',
            field=models.CharField(max_length=100, null=True, verbose_name='所属行业'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='ts_code',
            field=models.CharField(max_length=100, unique=True, verbose_name='TS代码'),
        ),
    ]
