# Generated by Django 2.2.7 on 2019-11-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wealth', '0003_auto_20191112_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='delist_date',
            field=models.DateField(max_length=100, null=True, verbose_name='退市日期'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='list_date',
            field=models.DateField(max_length=100, verbose_name='上市日期'),
        ),
    ]
