# Generated by Django 2.2.7 on 2019-11-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wealth', '0004_auto_20191112_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='所在地域'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='delist_date',
            field=models.DateField(blank=True, max_length=100, null=True, verbose_name='退市日期'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='所属行业'),
        ),
    ]
