# Generated by Django 2.2.7 on 2019-11-13 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wealth', '0006_auto_20191113_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dayk',
            old_name='hign',
            new_name='high',
        ),
    ]
